services:
  # standalone services
  user-service:
    restart: always
    extends:
      service: user-service
      file: ./user-service/docker-compose.yaml

  media-service:
    restart: always
    extends:
      service: media-service
      file: ./media-service/docker-compose.yaml

  # metadata services
  igdb-service:
    restart: always
    extends:
      service: igdb-service
      file: ./external-services/metadata/igdb/docker-compose.yaml

  hltb-service:
    restart: always
    extends:
      service: hltb-service
      file: ./external-services/metadata/hltb/docker-compose.yaml

  pcgw-service:
    restart: always
    extends:
      service: pcgw-service
      file: ./external-services/metadata/pcgw/docker-compose.yaml

  hardcover-service:
    restart: always
    extends:
      service: hardcover-service
      file: ./external-services/metadata/hardcover/docker-compose.yaml

  tmdb-service:
    restart: always
    extends:
      service: tmdb-service
      file: ./external-services/metadata/tmdb/docker-compose.yaml

  anilist-service:
    restart: always
    extends:
      service: anilist-service
      file: ./external-services/metadata/anilist/docker-compose.yaml

  metadata-service:
    restart: always
    image: nginx:latest
    container_name: metadata-service.mediamaster.internal
    hostname: metadata-service.mediamaster.internal
    depends_on:
      - igdb-service
      - hltb-service
      - pcgw-service
      - hardcover-service
      - tmdb-service
      - anilist-service
    volumes:
      - "./external-services/metadata/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8100:8100"
    networks:
      - mediamaster-internal-network

  # import services
  steam-import-service:
    restart: always
    extends:
      service: steam-import-service
      file: ./external-services/import/steam/docker-compose.yaml

  hardcover-import-service:
    restart: always
    extends:
      service: hardcover-import-service
      file: ./external-services/import/hardcover/docker-compose.yaml

  trakt-import-service:
    restart: always
    extends:
      service: trakt-import-service
      file: ./external-services/import/trakt/docker-compose.yaml

  mal-import-service:
    restart: always
    extends:
      service: mal-import-service
      file: ./external-services/import/mal/docker-compose.yaml

  import-service:
    restart: always
    image: nginx:latest
    container_name: import-service.mediamaster.internal
    hostname: import-service.mediamaster.internal
    depends_on:
      - steam-import-service
      - hardcover-import-service
      - trakt-import-service
      - mal-import-service
    volumes:
      - "./external-services/import/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8200:8200"
    networks:
      - mediamaster-internal-network

  # backend
  backend:
    restart: always
    image: nginx:latest
    container_name: nginx.mediamaster.internal
    hostname: nginx.mediamaster.internal
    depends_on:
      - user-service
      - media-service
      - metadata-service
      - import-service
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8000:8000"
    networks:
      - mediamaster-internal-network

networks:
  mediamaster-internal-network:
    name: mediamaster-internal-network
