upstream steam_import_service {
    server steam-import-service.mediamaster.internal:8201;
}

upstream hardcover_import_service {
    server hardcover-import-service.mediamaster.internal:8202;
}

upstream trakt_import_service {
    server trakt-import-service.mediamaster.internal:8203;
}

upstream mal_import_service {
    server mal-import-service.mediamaster.internal:8204;
}

server {
    listen 8200;
    server_name external_import;

    resolver 127.0.0.11 valid=30s;

    proxy_set_header host $host;
    proxy_set_header x-real-ip $remote_addr;
    proxy_set_header x-forwarded-for $proxy_add_x_forwarded_for;
    proxy_set_header x-forwarded-host $server_name;
    proxy_set_header x-forwarded-proto $scheme;

    location /steam/ {
        proxy_pass http://steam_import_service/;
    }

    location /hardcover/ {
        proxy_pass http://hardcover_import_service/;
    }

    location /trakt/ {
        proxy_pass http://trakt_import_service/;
    }

    location /mal/ {
        proxy_pass http://mal_import_service/;
    }
}
